general:
  s3_regional_buckets: true
project:
  name: quickstart-aws-utility-meter-data-analytics-platform
  owner: quickstart@amazon.com
  regions:
    - us-east-1
    - us-east-2
    - us-west-2
    - eu-central-1
    - ca-central-1
    - ap-south-1
tests:
  full-test-all-regions:
    parameters:
      MasterUsername: awsuser
      MasterUserPassword: Override_1
      ClusterName: redshift-cluster-3
      RedshiftPort: 5439
      DBName: sample-data
      LandingzoneTransformer: default
      CreateLandingZoneS3Bucket: 'Yes'
      LandingZoneS3BucketName: 'sample-meter-data'
      AvailabilityZones: $[taskcat_getaz_2]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: quickstart-aws-utility-meter-data-analytics-platform/
      QSS3BucketRegion: $[taskcat_current_region]
    template: ./templates/main.template.yaml