=== Meter data format

The input meter data format is variable and can be adjusted as described in the section <<Customize this Quick Start,'Customize this Quick Start'>>. However, the sample input data format of the 'London Meter Reads' looks like the following:

[cols="1,1,1", options="header"]
.Input Schema
|===
|Field
|Type
|Format

|lclid|string|
|stdortou|string|
|datetime|string|yyyy-MM-dd HH:mm:ss.SSSSSSS
|kwh/hh (per half hour)|double|0.000
|acorn|string|
|acorn_grouped|string|
|===

=== Table schemas

This Quick Start uses the following table schema for ETL job, ML model training and API queries. This schema is also used in Amazon Redshift.

[cols="1,1,1,1", options="header"]
.Internal Schema
|===
|Field
|Type
|Mandatory
|Format

|meter_id| String| X|
|reading_value| double| X|0.000
|reading_type| String| X|AGG\|INT*
|reading_date_time| Timestamp| X|yyyy-MM-dd HH:mm:ss.SSS
|date_str| String|X| yyyyMMdd
|obis_code| String| |
|week_of_year| int| |
|month| int| |
|year| int| |
|hour| int| |
|minute| int| |
|===

AGG = Aggregated Reads

INT = Interval Reads

=== API inputs and outputs

The API endpoint can be found in the API Gateway Console. The base URL will look similar to the following:
https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/

==== Enery usage forecast

API endpoint and input JSON for energy consumption forecast for a specific meter is described below.
----
https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/forecast/<meter_id>?data_start=<>&data_end=<>&ml_endpoint_name=<>
----

.example curl command
[source,shell script]
----
curl https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/forecast/MAC004734?data_start=2013-05-01&data_end=2013-10-01&ml_endpoint_name=ml-endpoint-3d249a54-da4c-4fc6-a7f5-eabddf368f89
----

==== Anomaly detection

API endpoint and input JSON format to get energy usage anomaly for a specific meter in a given time range is described below.
----
https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/anomaly/<meter_id>?data_start=<>&data_end=<>&outlier_only=<>
----

.example curl command
[source,shell script]
----
curl https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/anomaly/MAC000005?data_start=2013-01-01&data_end=2013-12-31&outlier_only=0
----

==== Meter outage details

API endpoint and input JSON to get a list of past meter outages for the given timeframe, including geo-location data, is described below.
----
https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/outage?startDateTime=<>&endDateTime=<>
----

.example curl command
[source,shell script]
----
curl https://xxxxxxxx.execute-api.us-east-1.amazonaws.com/outage?start_date_time=2013-01-03 09:00:01&end_date_time=2013-01-03 10:59:59
----

==== Aggregation API
Aggregations get loaded in real time from Amazon Redshift over an API endpoint

consumption aggregations can be done on a daily, weekly or monthly basis for a certain year and meter:
----
https://xxxxxx.execute-api.us-east-1.amazonaws.com/consumption/<daily|weekly|monthly>/<year>/<meter_id>
----

.example curl command for monthly aggregated data:
[source,shell script]
----
curl https://xxxxxx.execute-api.us-east-1.amazonaws.com/consumption/monthly/2013/MAC001595
----
