AWSTemplateFormatVersion: "2010-09-09"
Description: "Create Aurora cluster (qs-1r18anahd)"

Resources:
  MeterDataAuroraDatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-amazon-aurora-postgresql/templates/aurora_postgres.template.yaml"
        - S3Region:
            !If [UsingDefaultBucket, !Ref "AWS::Region", !Ref QSS3BucketRegion]
          S3Bucket:
            !If [
              UsingDefaultBucket,
              !Sub "${QSS3BucketName}-${AWS::Region}",
              !Ref QSS3BucketName,
            ]
      Parameters:
        DBMasterUsername: !Ref AdminUsername
        DBMasterUserPassword: !Ref AdminUserPassword
        VPCID: !Ref VPCID
        Subnet1ID: !Ref Subnet1ID
        Subnet2ID: !Ref Subnet2ID
        DBAccessCIDR: !Ref RemoteAccessCIDR
        DBMultiAZ: !Ref DBMultiAZ
        DBInstanceClass: !Ref DBInstanceClass
        DBName: !Ref DBName
        EnableEventSubscription: "false"
        DBEngineVersion: !Ref DBEngineVersion

  AuroraGlueConnectSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Aurora cluster to help Glue connect to the cluster
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !GetAtt MeterDataAuroraDatabaseStack.Outputs.RDSEndPointPort
          ToPort: !GetAtt MeterDataAuroraDatabaseStack.Outputs.RDSEndPointPort
          CidrIp: !Ref RemoteAccessCIDR
          Description: "Aurora Access to VPC CIDR"

  AuroraGlueSelfReferencingIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Self referencing security group ingress rule for Aurora cluster
      FromPort: -1
      GroupId: !Ref AuroraGlueConnectSecurityGroup
      IpProtocol: "-1"
      SourceSecurityGroupId: !Ref AuroraGlueConnectSecurityGroup
      ToPort: -1

  #
  # Glue Connection, Job, Trigger
  #
  MeterDataAuroraGlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: Workflow for copying meter reads to aurora

  MeterDataAuroraGlueConnection:
    Type: AWS::Glue::Connection
    DependsOn:
      - MeterDataAuroraDatabaseStack
      - AuroraGlueIAMRole
    Properties:
      ConnectionInput:
        Description: "A connection to the meter data Aurora cluster"
        ConnectionType: "JDBC"
        PhysicalConnectionRequirements:
          SubnetId: !Ref Subnet1ID
          SecurityGroupIdList:
            - !Ref AuroraGlueConnectSecurityGroup
          AvailabilityZone: !Select
            - 0
            - !GetAZs
              Ref: "AWS::Region"
        ConnectionProperties:
          "JDBC_CONNECTION_URL": !Sub "jdbc:postgresql://${MeterDataAuroraDatabaseStack.Outputs.RDSEndPoints}"
          "JDBC_ENFORCE_SSL": "false"
          PASSWORD: !Ref AdminUserPassword
          USERNAME: !Ref AdminUsername
      CatalogId: !Ref "AWS::AccountId"

  AuroraGlueIAMRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/service-role/"
      AssumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"glue.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSGlueServiceRole"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonRDSFullAccess"

  BusinessDailyToAuroraGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Role: !GetAtt AuroraGlueIAMRole.Arn
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://${GlueScriptsS3Bucket}/admin/business_daily_to_aurora.py"
        PythonVersion: "3"
      DefaultArguments:
        --TempDir: !Sub "s3://${GlueTempS3Bucket}/admin"
        --enable-metrics: ""
        --enable-continuous-cloudwatch-log: "true"
        --enable-continuous-log-filter: "true"
        --job-bookmark-option: "job-bookmark-enable"
        --job-language: "python"
        --enable-s3-parquet-optimized-committer: true
        --db_name: !Ref DBName
        --aurora_connection: !Ref MeterDataAuroraGlueConnection
        --temp_workflow_bucket: !Ref TempWorkflowS3Bucket
      Connections:
        Connections:
          - !Ref MeterDataAuroraGlueConnection
      MaxRetries: 0
      MaxCapacity: !Ref GlueDPU
      Timeout: 2880
      GlueVersion: "2.0"

  ImportDemoDataToAuroraGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Role: !GetAtt AuroraGlueIAMRole.Arn
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://${GlueScriptsS3Bucket}/admin/import_demo_data_to_aurora.py"
        PythonVersion: "3"
      DefaultArguments:
        --TempDir: !Sub "s3://${GlueTempS3Bucket}/admin"
        --enable-metrics: ""
        --enable-continuous-cloudwatch-log: "true"
        --enable-continuous-log-filter: "true"
        --job-bookmark-option: "job-bookmark-enable"
        --job-language: "python"
        --db_name: !GetAtt [MeterDataAuroraDatabaseStack, Outputs.DBName]
        --aurora_connection: !Ref MeterDataAuroraGlueConnection
        --cis_bucket: !Sub "${BusinessZoneS3Bucket}/cisdata"
        --geo_bucket: !Sub "${BusinessZoneS3Bucket}/geodata"
      Connections:
        Connections:
          - !Ref MeterDataAuroraGlueConnection
      MaxRetries: 0
      Timeout: 2880
      GlueVersion: "2.0"
      MaxCapacity: !Ref GlueDPU

  ExportToAuroraGlueTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type: "EVENT"
      WorkflowName: !Ref MeterDataAuroraGlueWorkflow
      Actions:
        - JobName: !Ref BusinessDailyToAuroraGlueJob

  InvokeGlueAuroraWflRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Glue-notify-events
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "glue:notifyEvent"
                Resource: !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:workflow/*"

  AuroraGlueWorkflowEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "EventRule for the Aurora Glue Workflow"
      EventPattern:
        source:
          - "aws.glue"
        detail-type:
          - "Glue Crawler State Change"
        detail:
          state:
            - "Succeeded"
          crawlerName:
            - !Ref GlueCrawlerToTriggerAfter
      State: "ENABLED"
      Targets:
        - Arn: !Sub "arn:${AWS::Partition}:glue:${AWS::Region}:${AWS::AccountId}:workflow/${MeterDataAuroraGlueWorkflow}"
          Id: !Ref MeterDataAuroraGlueWorkflow
          RoleArn: !GetAtt InvokeGlueAuroraWflRole.Arn

Outputs:
  StackName:
    Description: "Stack name"
    Value: !Sub "${AWS::StackName}"
  AuroraDatabaseEndpoint:
    Value: !GetAtt MeterDataAuroraDatabaseStack.Outputs.RDSEndPoints
  AuroraEndpoint:
    Value: !GetAtt MeterDataAuroraDatabaseStack.Outputs.RDSEndPoints

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, "aws-quickstart"]

Parameters:
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets.
      Only change this value if you customize or extend the Quick Start for your own use.
      This string can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*[/]$"
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/) and must terminate in a forward slash.
    Default: quickstart-aws-utility-meter-data-analytics-platform/
    Type: String
    Description:
      S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).

  AdminUsername:
    Type: String

  AdminUserPassword:
    Type: String
    NoEcho: True

  Subnet1ID:
    Type: AWS::EC2::Subnet::Id

  Subnet2ID:
    Type: AWS::EC2::Subnet::Id

  VPCID:
    Type: AWS::EC2::VPC::Id

  RemoteAccessCIDR:
    Type: String

  GlueCrawlerToTriggerAfter:
    Type: String

  GlueDPU:
    Type: String
    Description: No. of DPUs for Glue Job
    Default: 10

  GlueScriptsS3Bucket:
    Type: String

  GlueTempS3Bucket:
    Type: String

  BusinessZoneS3Bucket:
    Type: String

  TempWorkflowS3Bucket:
    Type: String

  QSS3BucketRegion:
    Type: String

  ClusterName:
    Type: String
    Default: Aurora-cluster-1

  DBInstanceClass:
    AllowedPattern: "db\\.[a-z0-9]*\\.[a-z0-9]*"
    ConstraintDescription: "Must select a valid database instance type."
    Default: db.r5.large
    Description: "The name of the compute and memory capacity class of the database instance."
    Type: String

  DBName:
    AllowedPattern: "[a-zA-Z0-9]*"
    Description: "Name of the Amazon Aurora database."
    MaxLength: "64"
    MinLength: "0"
    Default: "MeterDataAnalyticsDB"
    Type: String

  DBMultiAZ:
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
    Description: "Specifies if the database instance is a multiple Availability Zone deployment."
    Type: String

  DBEngineVersion:
    Description: Select Database Engine Version
    Type: String
    Default: 12.4
    AllowedValues:
      - 9.6.16
      - 9.6.17
      - 9.6.18
      - 9.6.19
      - 10.11
      - 10.12
      - 10.13
      - 10.14
      - 11.6
      - 11.7
      - 11.8
      - 11.9
      - 12.4
